version: "3.8"
networks:
  docknetwork:
services:
  authentication-server:
    hostname: authserver
    container_name: authserver
    build:
      context: .
      dockerfile: auth.Dockerfile
    ports:
      - "9735:9735"
    networks:
      - docknetwork
  returnhome-server:
    tty: true
    hostname: returnhome
    container_name: returnhome
    build:
      context: .
      dockerfile: returnhome.Dockerfile
    ports:
      - "10070:10070/udp"
    restart: on-failure
    networks:
      - docknetwork
  dnsmasq:
    hostname: dnsmasq
    container_name: dnsmasq
    build:
      context: .
      dockerfile: dns.Dockerfile
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    networks:
      - docknetwork
    cap_add:
      - NET_ADMIN
  gohttpserver:
    hostname: gohttpserver
    container_name: gohttpserver
    image: "druwadi13/gohttpserver"
    volumes:
      - C:/Users/TargetAcquired/source/repos/EQOAReturnHome:/app/public
    ports:
      - "7000:7000"
    networks:
      - docknetwork
  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.2
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1']
    environment:
      MARIADB_ROOT_PASSWORD: foobar
      MARIADB_DATABASE: eqoabase
      MARIADB_USER: fooUser
      MARIADB_PASSWORD: fooPass
    volumes:
      - ./docker-sql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - docknetwork
